# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'Manual trigger'
        required: false

jobs:
  run-demo-test:
    runs-on: ubuntu-latest
    steps:
    
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      
      - name: checkout test repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: run demo test using actions
        run: |
          chmod 777 install-requirements.sh
          sudo bash install-requirements.sh
          DEBIAN_FRONTEND=noninteractive
          bash testConfig.sh ${{ secrets.SLACK_TOKEN }}
